config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'registrations'}

  root 'pages#home'
  
  resources :users, only: [:show, :index]
  resources :friendships, only: [:create, :destroy, :accept] do
    member do
      put :accept
    end
  end

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
    belongs_to :user
    belongs_to :friend, class_name: "User"
    
    def accept_friendship
        self.update_attributes(state: "active", friended_at: Time.now)
    end
    
    def deny_friendship
       self.destroy 
    end
    
    def cancel_friendship
       self.destroy 
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  validates_presence_of :username
  validates_uniqueness_of :username
  
  has_many :friendships, dependent: :destroy
  has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id", dependent: :destroy
  
  def request_friendship(user_2)
    self.friendships.create(friend: user_2)
  end
  
  def pending_friend_requests_from
  	self.inverse_friendships.where(state: "pending")
  end
  
  def pending_friend_requests_to
  	self.friendships.where(state: "pending")
  end
  
  def active_friends
  	self.friendships.where(state: "active").map(&:friend) + self.inverse_friendships.where(state: "active").map(&:friend)
  end
  
  def friendship_status(user_2)
    friendship = Friendship.where(user_id: [self.id, user_2.id], friend_id: [self.id, user_2.id])
    unless friendship.any?
      return "not_friends"
    else
      if friendship.first.state == "active"
        return "friends"
      else
        if friendship.first.user == self
          return "pending"
        else
          return "requested"
        end
      end
    end
  end
  
  def friendship_relation(user_2)
    Friendship.where(user_id: [self.id, user_2.id], friend_id: [self.id, user_2.id]).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_user, only: [:create]
    before_action :set_friendship, only: [:destroy, :accept]
    
    
    def create
        @friendship = current_user.request_friendship(@user)
        respond_to do |format|
            format.html {redirect_to users_path, notice: "Friendship Created"}
        end
    end
    
    def destroy
        @friendship.destroy
        respond_to do |format|
            format.html {redirect_to users_path, notice: "Friendship Deleted"}
        end
    end
    
    def accept
        @friendship.accept_friendship  
        respond_to do |format|
            format.html {redirect_to users_path, notice: "Friendship Accepted"}
        end
    end
    
    private
    
    def set_user
        @user = User.find(params[:user_id])
    end
    
    def set_friendship
        @friendship = Friendship.find(params[:id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private

	def sign_up_params
		params.require(:user).permit(:email, :password, :password_confirmation, :username)
	end

	def account_update_params
		params.require(:user).permit(:email, :password, :password_confirmation, :username, :current_password, :age, :bio, :gender)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only:[:index] 
  before_action :set_user, only:[:show]
  
  def index
    case params[:people] when "friends"
    @users = current_user.active_friends
    when "requests"
    @users = current_user.pending_friend_requests_from.map(&:user)
    when "pending"
    @users = current_user.pending_friend_requests_to.map(&:friend)
    else
    @users = User.where.not(id: current_user.id)
    end
  end
  
  def show
  end
  
  private
  
  def set_user
    @user = User.find_by(username: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def action_buttons(user)
        case current_user.friendship_status(user) when "friends"
        link_to "Cancel Friendship", friendship_path(current_user.friendship_relation(user)), method: :delete
        when "pending"
        link_to "Cancel Request", friendship_path(current_user.friendship_relation(user)), method: :delete
        when "requested"
        link_to "Accept", accept_friendship_path(current_user.friendship_relation(user)), method: :put
        when "not_friends"
        link_to "Add as a Friend", friendships_path(user_id: user.id), method: :post
        end
    end
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Stukbook", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav"></ul>
      
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
        <li><a href="#">Timeline</a></li>
        <li><%= link_to "People", users_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> <%= gravatar_tag current_user.email, size: 20 %> <%= current_user.username %> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Profile", user_path(current_user.username) %></li>
            <li><a href="#">Friends</a></li>
            <li><%= link_to "Settings", edit_user_registration_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stukbook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/header" %>
<% flash.each do |type, message| %>
  <div class="alert alert-info fade-in">
    <button class="close" data-dismiss="alert">x</button>
    <%= message %>
  </div>
<% end %>
<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/users/_user.html.erb
<div class="col-md-3">
    <div class="thumbnail">
        <%= link_to user_path(user.username) do %>
            <%= gravatar_tag user.email, size: 200 %>
        <% end %>
        <div class="caption">
            <h3><%=user.username %></h3>
            <% if current_user %>
                <p><%= action_buttons(user) %></p>
            <% end %>
        </div>    
    </div>
</div>

app/views/users/index.html.erb
<div class="jumbotron">
    <h2>People</h2>
    <div class="btn-group" role="group" aria-label="Default Button Groups">
        <%= link_to "Everyone", users_path, class: "btn btn-default #{'active' unless params[:people]}" %>
        <%= link_to "Friends", users_path(people: "friends"), class: "btn btn-default #{'active' if params[:people] == 'friends'}" %>
        <%= link_to "Requests", users_path(people: "requests"), class: "btn btn-default #{'active' if params[:people] == 'requests'}" %>
        <%= link_to "Pending", users_path(people: "pending"), class: "btn btn-default #{'active' if params[:people] == 'pending'}" %>
    </div>
</div>

<div class="container">
    <div class="row">
        <%= render @users %>
    </div>
</div>

app/views/users/show.html.erb
<div class="jumbtron">
    <div class="container">
    
        <div class="row">
        
            <div class="col-md-4">
                <%= gravatar_tag @user.email, size: 200 %>
            </div>
        
            <div class="col-md-4">
              	<h3><%= @user.username %></h3>
              	<p>Age: <%= @user.age %></p>
              	<p>Gender: <%= @user.gender %> </p>
            </div>	
        
            <div class="col-md-4">
            	<h3>Who am I</h3>
            	<small><%= @user.bio %></small>
            </div>		
        
        </div>
    
    </div>
</div>